// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://laklhckyddyqmqubvslm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxha2xoY2t5ZGR5cW1xdWJ2c2xtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTgzNjgsImV4cCI6MjA2NTczNDM2OH0.UOc4s0yAkSLo9h4rwxh4fZwhYwxsyXHkk-Z5gPe4WHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);